#!/bin/bash

# A script to wrap sync commands for auto-building, cron, etc.
echo "Running automatic repository syncronization..."

# source user environment
source ~/.profile
source ~/.bashrc

# source Chromium OS environment
source ~/bin/environment/host.sh

# repo sync
~/bin/sync_sources
