#!/bin/bash

# Can use:
#  export BUILD=new or export BUILD=force
# Before running, for new builds. 
# Or, you can set the crosbuild option here.
[ $BUILD ] || BUILD=""

set -o errexit

# Needs environment.
# source ~/build/environment/host.sh

# Needs to be in source repo.
if [ "$(pwd)" != "${SOURCE_REPO}" ]; then
    cd ${SOURCE_REPO}
fi

# Enter chroot and autobuild.
cros_sdk -- ~/build/crosbuild ${BUILD}

exit $?
