#!/bin/bash
#
# This build assumes google API keys
# (in ~/.googleapikeys)

# Needs git information
if [ $# -eq 2 ]; then
    echo "USAGE: $(basename $0) [gitusername] [email@address.com]"
    exit 1
fi

# autosetup
install_git_and_curl
configure_git "$@"
tweak_sudoers_config
install_depot_tools
get_source_code
exit $?
