#!/bin/bash

## BEGIN DEFAULT CHROMIUM OS BUILD ENVIRONMENT

[ $BOARD ] || BOARD=cyan
[ $IMAGE ] || IMAGE=base
[ $VERITY ] || VERITY=on
[ $USBDEV ] || USBDEV=/dev/sdc

## END DEFAULT CHROMIUM OS BUILD ENVIRONMENT

# Needs to be in builddir
check_build_dir() {
    local builddir=~/trunk/src/scripts
    if [ "$(pwd)" != "$builddir" ]; then
        cd $buildir
    fi
}

setup_board() {
    echo -e "\n${colg}>>>${res} Setting up board..."
    ./setup_board --board=${BOARD}
}

build_packages() {
    echo -e "\n${colg}>>>${res} Building packages..."
    ./build_packages --board=${BOARD}
}

build_image() {
    # determine boot verification
    case "$VERITY" in
        on) :;;
        off) __verity__='--noenable-rootfs-verification';;
        *) echo 'Unable to determine $VERITY'; exit 1;;
    esac

    # build
    echo -e "\n${colg}>>>${res} Building image..."
    ./build_image --board=${BOARD} __$verity__ ${IMAGE}
}

flash_image(){
    # check for block device
    if [ $# -eq 1 ] && [ -b $1 ]; then
        echo -e "\n${colg}>>>${res} Flashing to usb..."
        cros flash usb://${USBDEV} ../build/images/${BOARD}/latest/chromiumos_${IMAGE}_image.bin
        return 0
    fi
    echo "Needs a proper usb device..."
    return 1
}

show_usage() {
    echo "$PROG - $DESC"
    echo
    echo "USAGE:"
    echo "   $PROG [OPTION]"
    echo
    echo "OPTIONS:"
    echo "   -a,--all       perform all operations"
    echo "   -b,--board     setup board"
    echo "   -h,--help      show (this) usage information"
    echo "   -p,--packages  build all packages for board"
    echo "   -i,--image     build disk image"
    echo "   -f,--flash     flash disk image to usb"
    echo
    echo "EXAMPLES:"
    echo "   $PROG -a"
    echo "   $PROG -b -p -i -f"
    echo
}

# Check return value, and give the a user message.
check_returns(){
    if [ $? -eq 0 ]; then
        echo -e "\n${colg}Success.${res}"
        return 0
    fi

    echo "\n${colr}Failed.${res}"
    return 1
}

# Global options
PROG=$(basename $0)
DESC='automatic builds for Chromium OS'
uopts="abhpif"
gopts="all,board,help,packages,image,flash"
opts=$(getopts -o $uopts -l $gopts -n "$PROG" -- "$@")
[ $? -eq 0 ] || { exit 1 ;}

if [ $# -eq 0 ]; then
    show_usage
    exit 1
fi

while true; do case "$1" in
    -a|--all)
        if setup_board && build_packages && build_image; then
            flash_image
        fi
        check_returns; break;;
    -b|--board) setup_board; check_returns; break;;
    -p|--packages) build_packages; check_returns; break;;
    -i|--image) build_image; check_returns; break;;
    -f|--flash) flash_image; check_returns; break;;
    *) show_usage; break;;
esac done

exit $?
