#!/bin/bash

if [ $# -eq 1 ] && { [ "$1" == "-m" ] || [ "$1" == "--mnt" ] ;}; then
    echo "Adding encrypted storage..."
    sudo cryptsetup luksOpen ${CRYPTDEV} ${CRYPTMAP}
    sudo mount /dev/mapper/${CRYPTMAP} ${CRYPTMNT}
elif [ $# -eq 1 ] && { [ "$1" == "-u" ] || [ "$1" == "--umnt" ] ;}; then
    echo "Removing encrypted storage..."
    sudo umount ${CRYPTMNT}
    sudo cryptsetup luksClose ${CRYPTMAP}
else
    echo "USAGE: $(basename $0) [-m,--mnt] [-u,--umnt]"
fi

