#!/bin/bash
#
# If your chromiumos source is located on a different drive,
# (and also encrypted using cryptsetup).

link_source() {
    ln -s ${HOSTCRYPT}/${CRYPTSRC} ${SOURCE_REPO}
}

unmount_cryptdev() {
    # Unmount device
    echo "Unmounting..."
    sudo umount ${HOSTCRYPT}
}

mount_cryptdev() {
    # Open device
    echo "Opening crypt device..."
    sudo cryptsetup luksOpen ${CRYPTDEV} ${CRYPTMAP}

    # Mount device
    echo "Mounting..."
    sudo mount /dev/mapper/${CRYPTMAP} ${HOSTCRYPT}

    # link
    if [ $LINK -eq 1 ]; then
        link_source
    fi
}

show_usage() {
    echo "$PRG - $DESC"
    echo
    echo "USAGE:"
    echo "   $PRG [OPTION]"
    echo
    echo "OPTIONS:"
    echo "   -u,--unmount  unmount device"
    echo "   -m,--mount    mount device"
    echo "   -s,--sym      symbolically link device to SOURCE_REPO"
    echo "   -h,--help     show (this) usage information"
    echo
    echo "EXAMPLES:"
    echo "   $PRG -m -l"
    echo "   $PRG -u"
    echo
}

PRG=$(basename $0)
DESC='in case your source is encrypted on another drive'
gopt="mount,unmount,link,help"
LINK=0
uopt="mulh"
opts=$(getopt -o $uopt -l $gopt -n "$PROG" -- "$@")
[ $? -eq 0 ] || { exit 1 ;}

if [ $# -eq 0 ]; then
    show_usage; exit 1
fi

eval set -- "$opts"

while true; do case "$1" in
    -l|--link) LINK=1; shift 2; break;;
    -m|--mount) mount_cryptdev; break;;
    -u|--unmount) unmount_cryptdev; break;;
    --) shift; break;;
    *) show_usage; exit 1; break;;
esac done

exit $?
