## BEGIN DEPOT_TOOLS ENVIRONMENT:

DEPOT_TOOLS ?= $(HOME)/depot_tools

## END DEPOT_TOOLS ENVIRONMENT.
## BEGIN CHROMIUM ENVIRONMENT:

CHROMIUM_SRC ?= $(HOME)/chromium
CHROMIUM_PATH := $(HOME)/bin:$(PATH):${DEPOT_TOOLS}

## END CHROMIUM ENVIRONMENT.
## BEGIN CHROMIUM OS ENVIRONMENT:

SOURCE_REPO ?= $(HOME)/chromiumos
REPOSYNC ?= -j8
CHROMIUMOS_PATH := $(CHROMIUM_PATH)

BOARD ?= cyan
IMAGE ?= base
VERITY ?= on

## END CHROMIUM OS ENVIRONMENT.

chromiumos: $(DEPOT_TOOLS) $(SOURCE_REPO)
	./chromiumos-autobuild
