#!/bin/bash

# Needs server environment
if ! echo "${DEVSERVER_PORT} ${SOURCE_REPO}" >& /dev/null; then
    echo "Failed to determine devserver environment..."
    exit 1
fi

# If already inside the chroot, start devserver.
# Otherwise, enter the chroot first.
if lsblk | grep -q cros >& /dev/null; then
    if [ -f /etc/cros_chroot_version ]; then
        start_devserver --port ${DEVSERVER_PORT}
    fi
fi

# needs to be in source repo
if [ "$(pwd)" != "${SOURCE_REPO}" ]; then 
    cd ${SOURCE_REPO}
fi

start_chroot -- start_devserver --port ${DEVSERVER_PORT}
