#!/bin/bash

## BEGIN CHROMIUM OS BUILD CHROOT ENVIRONMENT:

export PATH=~/bin:${PATH}

export BOARD=cyan
export IMAGE=base
export VERITY=on
export PERFORMANCE=1

## END CHROMIUM OS BUILD CHROOT ENVIRONMENT.
