#!/bin/bash

## BEGIN CHROMIUM OS DEV SERVER ENVIRONMENT:

export DEVSERVER_IP=192.168.6.105
export DEVSERVER_PORT=8855

export CHROMEOS_VERSION_DEVSERVER=http://${DEVSERVER_IP}:${DEVSERVER_PORT}
export CHROMEOS_VERSION_AUSERVER=http://${DEVSERVER_IP}:${DEVSERVER_PORT}/updates
export CHROMEOS_RELEASE_TRACK="stable-channel"
export CHROMEOS_RELEASE_BOARD="${BOARD}"
export NAME="Chromium OS (lothrond)"

## END CHROMIUM OS DEV SERVER ENVIRONMENT.
