#!/bin/bash
#
# Board name
# BOARD=""
#
# Package ebuild name.
# (example: PACKAGE="chromeos-base/mems_setup")
#
# Branch created locally for patching/testing (i.e. BRANCH=test-patch-00)
# (example: BRANCH="fix-battery-00")
#
# Intended for a simple one-lined patch command: (i.e. repo download, git pull, etc.)
# (example: PATCH="repo download 45723455/8")
#
# Disk image type: (dev, base, or test)
# (example: IMAGE="dev")
#
# boot verification:
# off - disable rootfs verification for read/write access.
# on - enable rootfs verification for read-only access.
# (example: VERITY="off)"
#
#======================================================================================
#
#PACKAGE=""
#BRANCH=""
#PATCH=""
#BOARD=${BOARD}
#IMAGE=${IMAGE}
#VERITY=${VERITY}
